#spring.application.name=qlpr
#server.port=8081
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=graphql
#spring.datasource.username=postgres
#spring.datasource.password=3435
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




spring.application.name=qlpr
server.port=8081
spring.datasource.url=jdbc:postgresql://mainsh-pg.cze4u8yy0a1s.ap-south-1.rds.amazonaws.com:5432/postgres?currentSchema=graphql
spring.datasource.username=postgres
spring.datasource.password=prabhat112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




